### ISSUE TITLE
Calling ArrayQueue.get() does not clear memory

### ISSUE THREAD

**Issue by jrj99** [portugueslab/arrayqueues#1]
Hi! I think you're project is very convenient for putting numpy arrays into threads.

However, I have noticed a bug that is slightly annoying. Calling ArrayQueue.get() does not truly clear the array out. Trying to insert an array of the same size back into a "cleared" array results in a memory error. Check out the code below: ArrayQueue.empty() returns true, even though the array is not truly cleared.

```
from arrayqueues.shared_arrays import ArrayQueue
import threading
import numpy as np
import time

class ReadProcess(threading.Thread):
    def __init__(self, queue):
        super().__init__()
        self.queue = queue
      
    def run(self):
        a = self.queue.get()
        print("Is queue empty (from child thread): {}".format(queue.empty()))

if __name__ == "__main__":
    create_start = time.time()
    queue = ArrayQueue(8/1000) # intitialises an ArrayQueue which can hold 8 KB of data
    numbers = np.random.uniform(10000, size = 1000)
    numbers_copy = np.copy(numbers)
    queue.put(numbers_copy)
    thread = ReadProcess(queue)
    thread.start()
    thread.join()
    print("Is queue empty(from main thread): {}".format(queue.empty()))
    queue.put(numbers_copy)
    queue.get()
    create_end = time.time()
    print("execution time: {}".format(create_end - create_start))
```

Here is the output of the error:

Is queue empty (from child thread): True
Is queue empty(from main thread): True
Traceback (most recent call last):
  File "array_queue_bug.py", line 25, in <module>
    queue.put(numbers_copy)
  File "C:\Users\jjones\AppData\Local\Programs\Python\Python37\lib\site-packages\arrayqueues\shared_arrays.py", line 71, in put
    self.check_full()
  File "C:\Users\jjones\AppData\Local\Programs\Python\Python37\lib\site-packages\arrayqueues\shared_arrays.py", line 63, in check_full
    self.view.i_item, self.last_item))
queue.Full: Queue of length 1 full when trying to insert 0, last item read was 0

**Comment by vilim** [comment]
This is a very special case which occurs, as far as I can deduce, only when you make the queue fit exactly one element. This is far from the use cases this package is considered for, however if it proves necessary, I can try to figure out a consistent way to handle this. 

For sharing a single array, consider a thin wrapper around the multiprocessing Array class, like ArrayView in this package. 

Lastly, if you use threading, this is not even necessary, as due to the python global interpreter lock only one thread per process is allowed. So there are no real separate threads and no need arises to consider memory sharing, as I think all memory should be accessible to all "threads", of course without the parallelization benefits.

**Comment by jrj99** [comment]
I tried increasing the queue size so that it was 4x as large as the array i was storing in the queue. This test code (which has an infinite loop that gets, then puts an array) will crash in about 10 seconds. I increased the queue buffer to 8x the array size i was inserting, and i was able to get the test code to run without crashing. Allocating less memory than this (less memory than 8x the array size) to the arrayqueue would result in a crash. Here is my test code:

```
from arrayqueues.shared_arrays import ArrayQueue
import threading
import numpy as np
import time

class ReadProcess(threading.Thread):
    def __init__(self, queue):
        super().__init__()
        self.queue = queue
      
    def run(self):
        a = self.queue.get()
        print("Is queue empty (from child thread): {}".format(queue.empty()))

if __name__ == "__main__":
    create_start = time.time()
    queue = ArrayQueue(32/1000) # intitialises an ArrayQueue which can hold 32 KB of data
    numbers = np.random.uniform(10000, size = 1000)  #this is 8 KB in size
    numbers_copy = np.copy(numbers)
    queue.put(numbers_copy)
    thread = ReadProcess(queue)
    thread.start()
    thread.join()
    print("Is queue empty(from main thread): {}".format(queue.empty()))
    while True:  #infinite loop, this code is used to test for memory crashes
        queue.put(numbers_copy)
        queue.get()
    create_end = time.time()
    print("execution time: {}".format(create_end - create_start))
```

**Comment by vigji** [comment]
Old issue, this does not seem to be crashing on my machine, I'll close for now.
