### ISSUE TITLE
causes code to get stuck

### ISSUE THREAD

**Issue by hazemati** [portugueslab/arrayqueues#2]
If I try to create a queue of 30 frames for a video that has a resolution of 1080p60 (1920x1080), the code never runs. I'm assuming that's stuck trying to allocate that much memory (I tried running this with SimpleQueue originally and had the same issue).

**Comment by hazemati** [comment]
Unit tested the array_queue  and confirmed that your code just gets stuck

**Comment by hazemati** [comment]
`
from arrayqueues.shared_arrays import ArrayQueue
import cv2
import unittest

class TestArrayQueuea(unittest.TestCase):
	def get_jpeg(self, file_name):
		return cv2.imread(file_name)
	def show_frame(self, frame):
		cv2.imshow("testing", frame) # 1 window for each RPi
		cv2.waitKey(0)

	def setUp(self):
		self.array_queue = ArrayQueue(1* 1920*1080)
		self.file_name = '/home/houman/Desktop/VVerm/vverm/Test/libraries/Camera/geese.jpg' 
		self.frame = self.get_jpeg(file_name)

	def test_output(self):
		self.array_queue.put(self.frame)
		received_frame = self.array_queue.get()
		self.show_frame(received_frame)		
if __name__ == '__main__':
	unittest.main()
`
sorry if the formatting on github is bad (I rarely every post bugs on github, and I'm not entirely sure how to do it properly).

**Comment by vigji** [comment]
I guess you spot the mistake - size of the queue should be passed in Mbytes, not in bytes. Closing, let me know if need reopening
