### ISSUE TITLE
dict objects support

### ISSUE THREAD

**Issue by pythondever** [portugueslab/arrayqueues#4]
how can i put dict objects into array?

**Comment by thomashirtz** [comment]
If you can have a dict of arrays instead of an array of dicts, you can use [treequeues](https://github.com/thomashirtz/treequeues)

**Comment by pythondever** [comment]
> If you can have a dict of arrays instead of an array of dicts, you can use [treequeues](https://github.com/thomashirtz/treequeues)

thanks，I will try it
